//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDCatalogDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playlist
    {
        public Playlist()
        {
            this.PlaylistSongs = new HashSet<PlaylistSong>();
        }
    
        public int PlaylistID { get; set; }
        public string PlaylistName { get; set; }
    
        public virtual ICollection<PlaylistSong> PlaylistSongs { get; set; }
    }
}
